.TH "C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/src Directory Reference" 3 "Sat Feb 28 2015" "Sr. Design 2015" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcommunication\&.c\fP"
.br
.ti -1c
.RI "file \fBeeprom\&.c\fP"
.br
.ti -1c
.RI "file \fBhid\&.c\fP"
.br
.ti -1c
.RI "file \fBmenu\&.c\fP"
.br
.ti -1c
.RI "file \fBmovement\&.c\fP"
.br
.ti -1c
.RI "file \fBpowerman\&.c\fP"
.br
.ti -1c
.RI "file \fBrtc\&.c\fP"
.br
.ti -1c
.RI "file \fBsensors\&.c\fP"
.br
.ti -1c
.RI "file \fBshared\&.c\fP"
.br
.ti -1c
.RI "file \fBsolarLight\&.c\fP"
.br
.in -1c
