.TH "C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/include Directory Reference" 3 "Sat Feb 28 2015" "Sr. Design 2015" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcommunication\&.h\fP"
.br
.ti -1c
.RI "file \fBeeprom\&.h\fP"
.br
.ti -1c
.RI "file \fBhid\&.h\fP"
.br
.ti -1c
.RI "file \fBmovement\&.h\fP"
.br
.ti -1c
.RI "file \fBpowerman\&.h\fP"
.br
.ti -1c
.RI "file \fBrtc\&.h\fP"
.br
.ti -1c
.RI "file \fBsensors\&.h\fP"
.br
.ti -1c
.RI "file \fBshared\&.h\fP"
.br
.ti -1c
.RI "file \fBsolarLight\&.h\fP"
.br
.in -1c
