.TH "C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/src/communication.c" 3 "Sat Feb 28 2015" "Sr. Design 2015" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/src/communication.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <shared\&.h>\fP
.br
\fC#include <communication\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcomm_start\fP ()"
.br
.ti -1c
.RI "void \fBcomm_flush\fP ()"
.br
.ti -1c
.RI "unsigned \fBcomm_tx\fP (unsigned char data)"
.br
.ti -1c
.RI "unsigned \fBcomm_go\fP ()"
.br
.ti -1c
.RI "unsigned char \fBcomm_rx\fP ()"
.br
.ti -1c
.RI "unsigned short \fBcomm_rx_word\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "unsigned char \fBrxBuff\fP [\fBRXBUFFSIZE\fP]"
.br
.ti -1c
.RI "unsigned char \fBtxBuff\fP [\fBTXBUFFSIZE\fP]"
.br
.ti -1c
.RI "unsigned char \fBrxPtrOut\fP"
.br
.ti -1c
.RI "unsigned char \fBtxPtrOut\fP"
.br
.ti -1c
.RI "unsigned char \fBrxPtrIn\fP"
.br
.ti -1c
.RI "unsigned char \fBtxPtrIn\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void comm_flush ()"

.SS "unsigned comm_go ()"
Activate transmission onto universe
.SS "unsigned char comm_rx (void)"

.SS "unsigned short comm_rx_word (void)"

.SS "void comm_start (void)"

.SS "unsigned comm_tx (unsigned char data)"

.SH "Variable Documentation"
.PP 
.SS "unsigned char rxBuff[\fBRXBUFFSIZE\fP]"

.SS "unsigned char rxPtrIn"

.SS "unsigned char rxPtrOut"

.SS "unsigned char txBuff[\fBTXBUFFSIZE\fP]"

.SS "unsigned char txPtrIn"

.SS "unsigned char txPtrOut"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sr\&. Design 2015 from the source code\&.
