.TH "comstat_t" 3 "Sat Feb 28 2015" "Sr. Design 2015" \" -*- nroff -*-
.ad l
.nh
.SH NAME
comstat_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <communication\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBTOKEN\fP: 1"
.br
.ti -1c
.RI "unsigned \fBTXOVER\fP: 1"
.br
.ti -1c
.RI "unsigned \fBRXOVER\fP: 1"
.br
.ti -1c
.RI "unsigned \fBTERROR\fP: 1"
.br
.ti -1c
.RI "unsigned \fB__pad0__\fP: 4"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned __pad0__"

.SS "unsigned RXOVER"

.SS "unsigned TERROR"

.SS "unsigned TOKEN"

.SS "unsigned TXOVER"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sr\&. Design 2015 from the source code\&.
