.TH "C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/include/eeprom.h" 3 "Sat Feb 28 2015" "Sr. Design 2015" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/include/eeprom.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <shared\&.h>\fP
.br
\fC#include <rtc\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEEPROMADDR\fP   0xA0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmem_start\fP (void)"
.br
.ti -1c
.RI "void \fBmem_check\fP (void)"
.br
.ti -1c
.RI "unsigned char \fBmem_append_log\fP (char)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EEPROMADDR   0xA0"

.SH "Function Documentation"
.PP 
.SS "unsigned char mem_append_log (char)"

.SS "void mem_check (void)"

.SS "void mem_start (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sr\&. Design 2015 from the source code\&.
