.TH "C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/src/hid.c" 3 "Sat Feb 28 2015" "Sr. Design 2015" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/src/hid.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <shared\&.h>\fP
.br
\fC#include <hid\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhid_setup\fP (void)"
.br
.RI "\fISets up the Human Interface Periphrials (keyboard, usb, and lcd) and their pins\&. \fP"
.ti -1c
.RI "void \fBhid_loop\fP (void)"
.br
.RI "\fIExecute the Maintainence Mode State Machine\&. Please see the State Machine Page\&. \fP"
.ti -1c
.RI "void \fBhid_execute\fP (unsigned char)"
.br
.ti -1c
.RI "void \fBlcd_begin\fP (void)"
.br
.ti -1c
.RI "void \fBlcd_menu\fP (unsigned char)"
.br
.ti -1c
.RI "void \fBlcd_execute\fP (unsigned char, unsigned char)"
.br
.ti -1c
.RI "void \fBlcd_usb\fP (unsigned char)"
.br
.ti -1c
.RI "void \fBlcd_end\fP (void)"
.br
.ti -1c
.RI "void \fBkey_isr\fP (void)"
.br
.ti -1c
.RI "void \fBkey_insertion\fP (void)"
.br
.ti -1c
.RI "void \fBkey_removal\fP (void)"
.br
.ti -1c
.RI "void \fBusb_isr\fP (void)"
.br
.ti -1c
.RI "void \fBusb_insertion\fP (void)"
.br
.ti -1c
.RI "void \fBusb_removal\fP (void)"
.br
.ti -1c
.RI "void \fBusb_begin\fP (void)"
.br
.ti -1c
.RI "void \fBusb_oneStatus\fP ()"
.br
.ti -1c
.RI "void \fBusb_myStatus\fP ()"
.br
.ti -1c
.RI "void \fBusb_allStatus\fP ()"
.br
.ti -1c
.RI "void \fBusb_end\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void hid_execute (unsigned char)"

.SS "void hid_loop (void)"

.PP
Execute the Maintainence Mode State Machine\&. Please see the State Machine Page\&. 
.SS "void hid_setup (void)"

.PP
Sets up the Human Interface Periphrials (keyboard, usb, and lcd) and their pins\&. 
.SS "void key_insertion (void)"

.SS "void key_isr (void)"

.SS "void key_removal (void)"

.SS "void lcd_begin (void)"

.SS "void lcd_end (void)"

.SS "void lcd_execute (unsigned char, unsigned char)"

.SS "void lcd_menu (unsigned char)"

.SS "void lcd_usb (unsigned char)"

.SS "void usb_allStatus ()"

.SS "void usb_begin (void)"

.SS "void usb_end (void)"

.SS "void usb_insertion (void)"

.SS "void usb_isr (void)"

.SS "void usb_myStatus ()"

.SS "void usb_oneStatus ()"

.SS "void usb_removal (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sr\&. Design 2015 from the source code\&.
