.TH "i2cPacket" 3 "Sat Feb 28 2015" "Sr. Design 2015" \" -*- nroff -*-
.ad l
.nh
.SH NAME
i2cPacket \- The first status byte - Includes the two state machine states, the rtc initialization state, and whether or not the loop will sleep at the end\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shared\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBaddr\fP"
.br
.ti -1c
.RI "unsigned char \fBdata\fP []"
.br
.ti -1c
.RI "unsigned char \fBdataLength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The first status byte - Includes the two state machine states, the rtc initialization state, and whether or not the loop will sleep at the end\&. 
.SH "Field Documentation"
.PP 
.SS "unsigned char addr"

.SS "unsigned char data[]"

.SS "unsigned char dataLength"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sr\&. Design 2015 from the source code\&.
