.TH "lcdEntry" 3 "Sat Feb 28 2015" "Sr. Design 2015" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lcdEntry \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBline1\fP [20]"
.br
.ti -1c
.RI "char \fBline2\fP [20]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char line1[20]"

.SS "char line2[20]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sr\&. Design 2015 from the source code\&.
