.TH "C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/src/menu.c" 3 "Sat Feb 28 2015" "Sr. Design 2015" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/src/menu.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <hid\&.h>\fP
.br
\fC#include <sensors\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBlcdEntry\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmenu1\fP ()"
.br
.ti -1c
.RI "void \fBmenu2\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBmenuEntries\fP []"
.br
.RI "\fIContains each entry for the menu\&. This is a constant\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void menu1 ()"

.SS "void menu2 ()"

.SH "Variable Documentation"
.PP 
.SS "const char* menuEntries[]"
\fBInitial value:\fP
.PP
.nf
= {"Exit M-Mode        ", 
                             "Light Settings     "  
                            }
.fi
.PP
Contains each entry for the menu\&. This is a constant\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Sr\&. Design 2015 from the source code\&.
