.TH "C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/src/movement.c" 3 "Sat Feb 28 2015" "Sr. Design 2015" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/src/movement.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <movement\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmovement_initialize\fP (void)"
.br
.ti -1c
.RI "void \fBmovement_test\fP (void)"
.br
.ti -1c
.RI "void \fBdaytime_move\fP (void)"
.br
.ti -1c
.RI "void \fBdusk_moveback\fP (void)"
.br
.ti -1c
.RI "void \fBseasonal_adjust\fP (void)"
.br
.ti -1c
.RI "void \fBmaintenance_move\fP (unsigned char)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void daytime_move (void)"

.SS "void dusk_moveback (void)"

.SS "void maintenance_move (unsigned char)"

.SS "void movement_initialize (void)"

.SS "void movement_test (void)"

.SS "void seasonal_adjust (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sr\&. Design 2015 from the source code\&.
