.TH "C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/include/rtc.h" 3 "Sat Feb 28 2015" "Sr. Design 2015" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/include/rtc.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBREFDAY\fP   2"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrtc_start\fP (void)"
.br
.ti -1c
.RI "void \fBrtc_set\fP (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define REFDAY   2"

.SH "Function Documentation"
.PP 
.SS "void rtc_set (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)"

.SS "void rtc_start (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sr\&. Design 2015 from the source code\&.
