.TH "C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/src/rtc.c" 3 "Sat Feb 28 2015" "Sr. Design 2015" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/src/rtc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <shared\&.h>\fP
.br
\fC#include <rtc\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned char \fBchar2bcd\fP (unsigned char)"
.br
.ti -1c
.RI "unsigned char \fBweekday\fP (unsigned char, unsigned char, unsigned char)"
.br
.ti -1c
.RI "void \fBrtc_start\fP ()"
.br
.ti -1c
.RI "unsigned char \fBrtc_set\fP (unsigned char year, unsigned char month, unsigned char day, unsigned char hour, unsigned char minute, unsigned char second)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned char char2bcd (unsigned char in)"

.SS "unsigned char rtc_set (unsigned char year, unsigned char month, unsigned char day, unsigned char hour, unsigned char minute, unsigned char second)"

.SS "void rtc_start (void)"

.SS "unsigned char weekday (unsigned char year, unsigned char month, unsigned char day)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sr\&. Design 2015 from the source code\&.
