.TH "C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/src/sensors.c" 3 "Sat Feb 28 2015" "Sr. Design 2015" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/src/sensors.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sensors\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsensor_start\fP (void)"
.br
.ti -1c
.RI "unsigned short \fBphoto_value\fP (unsigned char photonum)"
.br
.ti -1c
.RI "unsigned short \fBtemperature\fP (void)"
.br
.ti -1c
.RI "unsigned short \fBrotational_postion\fP (unsigned char potnum)"
.br
.ti -1c
.RI "void \fBpir_enable\fP (unsigned char pironoff)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned short photo_value (unsigned char photonum)"

.SS "void pir_enable (unsigned char pironoff)"

.SS "unsigned short rotational_postion (unsigned char potnum)"

.SS "void sensor_start (void)"

.SS "unsigned short temperature (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sr\&. Design 2015 from the source code\&.
