.TH "C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/include/sensors.h" 3 "Sat Feb 28 2015" "Sr. Design 2015" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/include/sensors.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPINIO_POT_LEFTRIGHT\fP   TRISAbits\&.TRISA2"
.br
.ti -1c
.RI "#define \fBPINIO_POT_UPDOWN\fP   TRISAbits\&.TRISA3"
.br
.ti -1c
.RI "#define \fBPINIO_LIGHTLEVEL\fP   TRISGbits\&.TRISG0"
.br
.ti -1c
.RI "#define \fBPINIO_YEARLEVEL\fP   TRISGbits\&.TRISG1"
.br
.ti -1c
.RI "#define \fBPINIO_DAYLEVEL1\fP   TRISGbits\&.TRISG2"
.br
.ti -1c
.RI "#define \fBPINIO_DAYLEVEL2\fP   TRISGbits\&.TRISG3"
.br
.ti -1c
.RI "#define \fBPINIO_TEMP\fP   TRISAbits\&.TRISA0"
.br
.ti -1c
.RI "#define \fBPINIO_PIR\fP   TRISCbits\&.TRISC6"
.br
.ti -1c
.RI "#define \fBPINIO_LIMIT_DOWN\fP   TRISGbits\&.TRISG4"
.br
.ti -1c
.RI "#define \fBPINIO_LIMIT_UP\fP   TRISFbits\&.TRISF2"
.br
.ti -1c
.RI "#define \fBPINIO_LIMIT_EAST\fP   TRISFbits\&.TRISF6"
.br
.ti -1c
.RI "#define \fBPINIO_LIMIT_WEST\fP   TRISFbits\&.TRISF7"
.br
.ti -1c
.RI "#define \fBPINAD_POT_LEFTRIGHT\fP   ANCON1bits\&.ANSEL2"
.br
.ti -1c
.RI "#define \fBPINAD_POT_UPDOWN\fP   ANCON1bits\&.ANSEL3"
.br
.ti -1c
.RI "#define \fBPINAD_LIGHTLEVEL\fP   ANCON1bits\&.ANSEL7"
.br
.ti -1c
.RI "#define \fBPINAD_YEARLEVEL\fP   ANCON2bits\&.ANSEL12"
.br
.ti -1c
.RI "#define \fBPINAD_DAYLEVEL1\fP   ANCON2bits\&.ANSEL13"
.br
.ti -1c
.RI "#define \fBPINAD_DAYLEVEL2\fP   ANCON2bits\&.ANSEL14"
.br
.ti -1c
.RI "#define \fBPINAD_TEMP\fP   ANCON1bits\&.ANSEL0"
.br
.ti -1c
.RI "#define \fBPINAD_LIMIT_DOWN\fP   ANCON2bits\&.ANSEL15"
.br
.ti -1c
.RI "#define \fBPINAD_LIMIT_UP\fP   ANCON1bits\&.ANSEL6"
.br
.ti -1c
.RI "#define \fBPINAD_LIMIT_EAST\fP   ANCON2bits\&.ANSEL10"
.br
.ti -1c
.RI "#define \fBPINAD_LIMIT_WEST\fP   ANCON2bits\&.ANSEL11"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsensor_start\fP (void)"
.br
.ti -1c
.RI "unsigned short \fBphoto_value\fP (unsigned char)"
.br
.ti -1c
.RI "unsigned short \fBtemperature\fP (void)"
.br
.ti -1c
.RI "unsigned short \fBrotational_postion\fP (unsigned char)"
.br
.ti -1c
.RI "void \fBpir_enable\fP (unsigned char)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PINAD_DAYLEVEL1   ANCON2bits\&.ANSEL13"

.SS "#define PINAD_DAYLEVEL2   ANCON2bits\&.ANSEL14"

.SS "#define PINAD_LIGHTLEVEL   ANCON1bits\&.ANSEL7"

.SS "#define PINAD_LIMIT_DOWN   ANCON2bits\&.ANSEL15"

.SS "#define PINAD_LIMIT_EAST   ANCON2bits\&.ANSEL10"

.SS "#define PINAD_LIMIT_UP   ANCON1bits\&.ANSEL6"

.SS "#define PINAD_LIMIT_WEST   ANCON2bits\&.ANSEL11"

.SS "#define PINAD_POT_LEFTRIGHT   ANCON1bits\&.ANSEL2"

.SS "#define PINAD_POT_UPDOWN   ANCON1bits\&.ANSEL3"

.SS "#define PINAD_TEMP   ANCON1bits\&.ANSEL0"

.SS "#define PINAD_YEARLEVEL   ANCON2bits\&.ANSEL12"

.SS "#define PINIO_DAYLEVEL1   TRISGbits\&.TRISG2"

.SS "#define PINIO_DAYLEVEL2   TRISGbits\&.TRISG3"

.SS "#define PINIO_LIGHTLEVEL   TRISGbits\&.TRISG0"

.SS "#define PINIO_LIMIT_DOWN   TRISGbits\&.TRISG4"

.SS "#define PINIO_LIMIT_EAST   TRISFbits\&.TRISF6"

.SS "#define PINIO_LIMIT_UP   TRISFbits\&.TRISF2"

.SS "#define PINIO_LIMIT_WEST   TRISFbits\&.TRISF7"

.SS "#define PINIO_PIR   TRISCbits\&.TRISC6"

.SS "#define PINIO_POT_LEFTRIGHT   TRISAbits\&.TRISA2"

.SS "#define PINIO_POT_UPDOWN   TRISAbits\&.TRISA3"

.SS "#define PINIO_TEMP   TRISAbits\&.TRISA0"

.SS "#define PINIO_YEARLEVEL   TRISGbits\&.TRISG1"

.SH "Function Documentation"
.PP 
.SS "unsigned short photo_value (unsigned char)"

.SS "void pir_enable (unsigned char)"

.SS "unsigned short rotational_postion (unsigned char)"

.SS "void sensor_start (void)"

.SS "unsigned short temperature (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sr\&. Design 2015 from the source code\&.
