.TH "C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/src/solarLight.c" 3 "Sat Feb 28 2015" "Sr. Design 2015" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Benjaminp/Documents/pcc/current/EL 450/PatienceInc/firmware/src/solarLight.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <xc\&.h>\fP
.br
\fC#include <solarLight\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmain\fP (void)"
.br
.RI "\fIRun setup and main loops\&. \fP"
.ti -1c
.RI "void \fBsetup\fP ()"
.br
.RI "\fIRun all the setup routines\&. \fP"
.ti -1c
.RI "void \fBloop\fP ()"
.br
.ti -1c
.RI "void interrupt low_priority \fBisr_low\fP ()"
.br
.ti -1c
.RI "void interrupt high_priority \fBisr_high\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void interrupt high_priority isr_high (void)"

.SS "void interrupt low_priority isr_low (void)"

.SS "void loop (void)"
/brief The MAIN loop that executes EVERYTHING!
.PP
No inputs or outputs besides what goes in and out of the pins\&. 
.SS "void main (void)"

.PP
Run setup and main loops\&. 
.SS "void setup (void)"

.PP
Run all the setup routines\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Sr\&. Design 2015 from the source code\&.
