.TH "statemachines" 3 "Sat Feb 28 2015" "Sr. Design 2015" \" -*- nroff -*-
.ad l
.nh
.SH NAME
statemachines \- State Machines 

.SH "The Day/Night State Machine"
.PP
There should be a picture here of the day/night state machine\&.
.SH "Maintainence Mode State Machine"
.PP
 
.SS "Mode 0: Standby"
.SS "Modes 1 and 3: Master Mode"
.SS "Mode 2: Slave Mode"

