Sr. Design 2015: C:/Users/Benjaminp/Documents/GitHub/firmware/src/communication.c File Reference
communication.c File Reference
This page includes the communications functions to talk to other poles via RS/EIA-485.
#include <shared.h>
#include <communication.h>
#include <eeprom.h>
#include "usb/usb_hal_pic18.h"
Functions
void comm_start ()
Setup the pins and modules for communication outside the pole.
void comm_flush ()
Flush both communications buffers.
unsigned comm_tx (unsigned char data, unsigned isAddress)
unsigned char comm_rx ()
Get a byte off the stack. Returns that byte.
unsigned short comm_rx_word ()
Get two bytes off the stack. Returns a short.
unsigned char comm_get_status (unsigned char addr)
void comm_loop ()
this is called by the main loop.exe
Detailed Description
This page includes the communications functions to talk to other poles via RS/EIA-485.
See baudrate note. Author: Benjamin Plain
Definition in file communication.c.
Function Documentation
void comm_flush (void)
Flush both communications buffers.
Definition at line 58 of file communication.c.
Referenced by comm_start(), and isr().
unsigned char comm_get_status (unsigned char addr)
Definition at line 118 of file communication.c.
void comm_loop ()
this is called by the main loop.exe
Definition at line 128 of file communication.c.
unsigned char comm_rx (void)
Get a byte off the stack. Returns that byte.
Todo:
TODO: Add buffer overflow detection (low priority for this system)
Definition at line 89 of file communication.c.
Referenced by comm_get_status(), and comm_rx_word().
unsigned short comm_rx_word (void)
Get two bytes off the stack. Returns a short.
Todo:
TODO: What happens if ther is no data there?
Definition at line 99 of file communication.c.
void comm_start (void)
Setup the pins and modules for communication outside the pole.
Todo:
TODO: Finish skeleton For communications
TODO[Review]: Communications (BEN)
Todo:
TODO: Communications start function
Use the last 3 bits of RCSTA1 for errors and 9th bit. Address that is received will be in RCREG1
Definition at line 18 of file communication.c.
unsigned comm_tx (unsigned char data, unsigned isAddress)
Addresses
255 - Reserved since all high bits
254 = Master is now active - Followed by the master's address
253 = Master is inactive
252 = Slave's turn to send
251 = Slave's turn is over
250 = GLOBAL ADDRESS
0-249 = pole's addresses. Assigned in maintainence mode or via dip switches.
Definition at line 71 of file communication.c.
Referenced by comm_get_status(), and comm_loop().