Sr. Design 2015: C:/Users/Benjaminp/Documents/GitHub/firmware.X/src/hid.c File Reference
hid.c File Reference
#include <shared.h>
#include <hid.h>
#include <lcd.h>
#include <string.h>
#include <communication.h>
Functions
void hid_setup (void)
Sets up the Human Interface Periphrials (keyboard, usb, and lcd) and their pins.
void hid_loop (void)
Execute the Maintainence Mode State Machine. Please see the State Machine Page.
unsigned lcd_begin (void)
void lcd_end (unsigned char NA)
display "exiting", then turn off the led, and exit maintainence mode
unsigned keypad_push (char keypress)
Push a keypad press to the keypad command FIFO.
unsigned char keypad_pull ()
Get the last command from the keypad Attribution: Code from pages 630-633 of "A First Book of ANSI C" by Bronson.
unsigned char keypad_size (void)
Give the size of the dynamic keypad FIFO.
unsigned keypad_flush (void)
Flush the keypad FIFO.
void usb_isr (void)
void usb_insertion (void)
void usb_removal (void)
void usb_begin (void)
void usb_oneStatus ()
void usb_myStatus ()
void usb_allStatus ()
void usb_end (void)
Function Documentation
void hid_loop (void)
Execute the Maintainence Mode State Machine. Please see the State Machine Page.
Definition at line 32 of file hid.c.
Referenced by loop().
void hid_setup (void)
Sets up the Human Interface Periphrials (keyboard, usb, and lcd) and their pins.
Todo:
TODO: initialize baud rate to 9600
Todo:
TODO: Josh. Put your stuff to setup USB here.
Definition at line 11 of file hid.c.
Referenced by setup().
unsigned keypad_flush (void)
Flush the keypad FIFO.
Definition at line 279 of file hid.c.
Referenced by lcd_begin().
unsigned char keypad_pull (void)
Get the last command from the keypad Attribution: Code from pages 630-633 of "A First Book of ANSI C" by Bronson.
Definition at line 251 of file hid.c.
Referenced by hid_loop(), lcd_begin(), menu_alarm_battery(), menu_alarm_comm(), menu_alarm_light(), menu_battVoltage(), menu_getSelection(), menu_seeTime(), menu_setACBatt(), menu_setAddr(), menu_setDimLength(), menu_setDimLevel(), menu_setHurricaneMode(), menu_setLightMode(), menu_setPanelMode(), menu_setTime(), and mhurricane().
unsigned keypad_push (char keypress)
Push a keypad press to the keypad command FIFO.
Definition at line 180 of file hid.c.
unsigned char keypad_size (void)
Give the size of the dynamic keypad FIFO.
Purpose: Size management, Debug
Output: the number of entries there are being used.
Definition at line 271 of file hid.c.
unsigned lcd_begin (void)
Todo:
FIXME: See if you can try to not have a potentially infinite loop within the main loop.
Definition at line 103 of file hid.c.
Referenced by hid_loop().
void lcd_end (unsigned char NA)
display "exiting", then turn off the led, and exit maintainence mode
Definition at line 163 of file hid.c.
void usb_allStatus ()
Definition at line 338 of file hid.c.
void usb_begin (void)
Definition at line 309 of file hid.c.
void usb_end (void)
Definition at line 342 of file hid.c.
void usb_insertion (void)
Definition at line 298 of file hid.c.
void usb_isr (void)
Definition at line 294 of file hid.c.
void usb_myStatus ()
Definition at line 334 of file hid.c.
void usb_oneStatus ()
Definition at line 330 of file hid.c.
void usb_removal (void)
Definition at line 302 of file hid.c.