Sr. Design 2015: C:/Users/Benjaminp/Documents/GitHub/firmware.X/src/lcd.c File Reference
lcd.c File Reference
#include <lcd.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <powerman.h>
Data Structures
struct specialChar
Macros
#define NUMMENUENTRIES 7
Functions
void lcd_setup ()
void lcd_usb (unsigned char enable)
display USB connected on lcd.
unsigned char lcd_display (unsigned char line, unsigned char data[21])
void lcd_background (unsigned char red, unsigned char green, unsigned char blue)
Change the color of the LCD backlight.
void menu_up (unsigned char none)
Change the pointer to which menu item we are displaying.
void menu_next (unsigned char none)
Change the pointer to next number or come around. Called by the down button.
void menu_prev (unsigned char none)
Go to the previous menu entry. Called by the up button.
void menu_enter ()
This function is run by pressing the enter key on the keypad.
void menu_display ()
void menu_getSelection ()
void menu_setLightMode (unsigned char id)
Set the light mode (full,dim,auto,off)
void menu_setHurricaneMode (unsigned char id)
Menu Function for activating hurricane mode.
void menu_setPanelMode (unsigned char id)
Lock the solar panel (Auto/Locked) Menu Function for activating hurricane mode.
void menu_setACBatt (unsigned char id)
AC/Battery switch.
void menu_seeTime (unsigned char na)
AC/Battery switch.
void menu_setXaxis (unsigned char id)
void menu_setYaxis (unsigned char id)
void menu_setTime (unsigned char na)
void menu_setDimLevel (unsigned char id)
void menu_setDimLength (unsigned char id)
void menu_setAddr (unsigned char id)
void menu_battVoltage (unsigned char id)
void menu_alarm_battery (unsigned char id)
Alarm for the battery: DONE!
void menu_alarm_light (unsigned char id)
void menu_alarm_comm (unsigned char id)
Variables
unsigned char lineData [21]
Macro Definition Documentation
#define NUMMENUENTRIES 7
Definition at line 23 of file lcd.c.
Referenced by menu_next(), and menu_prev().
Function Documentation
void lcd_background (unsigned char red, unsigned char green, unsigned char blue)
Change the color of the LCD backlight.
Todo:
FIXME: Change channels to correct numbers
Definition at line 285 of file lcd.c.
Referenced by lcd_begin(), lcd_end(), and lcd_usb().
unsigned char lcd_display (unsigned char line, unsigned char data[21])
Research into the ST7036
found a link (https://www.newhavendisplay.com/app_notes/NHD-C0220BiZ.txt)[https://www.newhavendisplay.com/app_notes/NHD-C0220BiZ.txt]
Definition at line 242 of file lcd.c.
Referenced by lcd_usb(), menu_alarm_battery(), menu_alarm_comm(), menu_alarm_light(), menu_battVoltage(), menu_display(), menu_getSelection(), menu_seeTime(), menu_setACBatt(), menu_setAddr(), menu_setDimLength(), menu_setDimLevel(), menu_setHurricaneMode(), menu_setLightMode(), menu_setPanelMode(), menu_setTime(), menu_setXaxis(), and menu_setYaxis().
void lcd_setup ()
Todo:
TODO: Make the menues into a Constant that resides in program memory.
Todo:
TODO: Remove "Initializing PIC" from the screen once it is done.
Todo:
TODO: Add functions to the menues. this is for EVERYONE to do. Contains each entry for the menu. This is a constant.
Definition at line 25 of file lcd.c.
Referenced by hid_setup().
void lcd_usb (unsigned char enable)
display USB connected on lcd.
Press the special key to disconnect.
Set Color to Blue
Then display USB Connected
Definition at line 229 of file lcd.c.
void menu_alarm_battery (unsigned char id)
Alarm for the battery: DONE!
Definition at line 1220 of file lcd.c.
void menu_alarm_comm (unsigned char id)
Definition at line 1328 of file lcd.c.
void menu_alarm_light (unsigned char id)
Definition at line 1304 of file lcd.c.
void menu_battVoltage (unsigned char id)
Definition at line 1185 of file lcd.c.
void menu_display ()
Definition at line 379 of file lcd.c.
Referenced by hid_loop(), lcd_begin(), and menu_next().
void menu_enter ()
This function is run by pressing the enter key on the keypad.
Todo:
TODO: Get the pole ID if the main menu items are not 0, 4, or 6.
Definition at line 359 of file lcd.c.
Referenced by hid_loop().
void menu_getSelection ()
Definition at line 411 of file lcd.c.
Referenced by menu_enter().
void menu_next (unsigned char none)
Change the pointer to next number or come around. Called by the down button.
Definition at line 316 of file lcd.c.
Referenced by hid_loop().
void menu_prev (unsigned char none)
Go to the previous menu entry. Called by the up button.
Definition at line 338 of file lcd.c.
Referenced by hid_loop().
void menu_seeTime (unsigned char na)
AC/Battery switch.
Todo:
TODO: If we ever get time, we need to make these functions non-blocking
Definition at line 820 of file lcd.c.
void menu_setACBatt (unsigned char id)
AC/Battery switch.
Definition at line 728 of file lcd.c.
void menu_setAddr (unsigned char id)
Definition at line 1135 of file lcd.c.
void menu_setDimLength (unsigned char id)
Definition at line 1082 of file lcd.c.
void menu_setDimLevel (unsigned char id)
Definition at line 1030 of file lcd.c.
void menu_setHurricaneMode (unsigned char id)
Menu Function for activating hurricane mode.
Definition at line 617 of file lcd.c.
void menu_setLightMode (unsigned char id)
Set the light mode (full,dim,auto,off)
Definition at line 520 of file lcd.c.
void menu_setPanelMode (unsigned char id)
Lock the solar panel (Auto/Locked) Menu Function for activating hurricane mode.
Definition at line 677 of file lcd.c.
Referenced by menu_setHurricaneMode().
void menu_setTime (unsigned char na)
Definition at line 892 of file lcd.c.
void menu_setXaxis (unsigned char id)
Definition at line 852 of file lcd.c.
void menu_setYaxis (unsigned char id)
Definition at line 872 of file lcd.c.
void menu_up (unsigned char none)
Change the pointer to which menu item we are displaying.
TODO: What if we are in the main menu?
Definition at line 299 of file lcd.c.
Referenced by hid_loop().
Variable Documentation
unsigned char lineData[21]
Definition at line 21 of file lcd.c.
Referenced by lcd_begin(), lcd_usb(), menu_alarm_battery(), menu_alarm_comm(), menu_alarm_light(), menu_getSelection(), menu_setACBatt(), menu_setAddr(), menu_setDimLength(), menu_setDimLevel(), menu_setHurricaneMode(), menu_setLightMode(), menu_setPanelMode(), menu_setXaxis(), and menu_setYaxis().