Sr. Design 2015: C:/Users/Benjaminp/Documents/GitHub/firmware/include/lcd.h File Reference
lcd.h File Reference
#include <hid.h>
#include <sensors.h>
#include <string.h>
#include <eeprom.h>
Data Structures
struct menuEntry
Functions
void menu_up (unsigned char)
Change the pointer to which menu item we are displaying.
void menu_next (unsigned char)
Change the pointer to next number or come around. Called by the down button.
void menu_prev (unsigned char)
Go to the previous menu entry. Called by the up button.
void menu_enter (unsigned char)
This function is run by pressing the enter key on the keypad.
void lcd_setup ()
void lcd_usb (unsigned char)
display USB connected on lcd.
unsigned char lcd_display (char[21], char[21])
void lcd_background (unsigned char, unsigned char, unsigned char)
Change the color of the LCD backlight.
Variables
menuEntry menu [7]
menue: The menu entries for the LCD.
Function Documentation
void lcd_background (unsigned char, unsigned char, unsigned char)
Change the color of the LCD backlight.
Todo:
FIXME: Change channels to correct numbers
Definition at line 142 of file lcd.c.
Referenced by lcd_begin(), and lcd_usb().
unsigned char lcd_display (char [21], char [21])
Research into the ST7036
found a link (https://www.newhavendisplay.com/app_notes/NHD-C0220BiZ.txt)[https://www.newhavendisplay.com/app_notes/NHD-C0220BiZ.txt]
Definition at line 105 of file lcd.c.
Referenced by lcd_begin(), lcd_end(), and lcd_usb().
void lcd_setup ()
Todo:
TODO: Make the menues into a Constant that resides in program memory.
Todo:
TODO: Remove "Initializing PIC" from the screen once it is done.
Todo:
TODO: Add functions to the menues. this is for EVERYONE to do. Contains each entry for the menu. This is a constant.
Todo:
FIXME: Can I use sprintf d?
Definition at line 14 of file lcd.c.
Referenced by hid_setup().
void lcd_usb (unsigned char enable)
display USB connected on lcd.
Press the special key to disconnect.
Set Color to Blue
Then display USB Connected
Definition at line 97 of file lcd.c.
void menu_enter (unsigned char)
This function is run by pressing the enter key on the keypad.
Definition at line 205 of file lcd.c.
void menu_next (unsigned char)
Change the pointer to next number or come around. Called by the down button.
Definition at line 165 of file lcd.c.
void menu_prev (unsigned char)
Go to the previous menu entry. Called by the up button.
Definition at line 185 of file lcd.c.
void menu_up (unsigned char)
Change the pointer to which menu item we are displaying.
TODO: What if we are in the main menu?
Definition at line 155 of file lcd.c.
Variable Documentation
menuEntry menu[7]
menue: The menu entries for the LCD.
Note that the 0th entry is the main menu.
Definition at line 35 of file lcd.h.
Referenced by menu_enter(), menu_next(), and menu_prev().