Sr. Design 2015: C:/Users/Benjaminp/Documents/GitHub/firmware.X/include/movement.h File Reference
movement.h File Reference
#include <shared.h>
#include <sensors.h>
Macros
#define PINIO_MOVE_LEFTRIGHT_1 TRISBbits.TRISB1
#define PINIO_MOVE_LEFTRIGHT_2 TRISBbits.TRISB2
#define PINIO_MOVE_LEFTRIGHT_3 TRISBbits.TRISB3
#define PINIO_MOVE_LEFTRIGHT_4 TRISBbits.TRISB4
#define PINIO_MOVE_UPDOWN_1 TRISDbits.TRISD4
#define PINIO_MOVE_UPDOWN_2 TRISDbits.TRISD5
#define PINIO_MOVE_UPDOWN_3 TRISDbits.TRISD6
#define PINIO_MOVE_UPDOWN_4 TRISDbits.TRISD7
#define PIN_MOVE_UP_1 PORTDbits.RD7
#define PIN_MOVE_UP_2 PORTDbits.RD4
#define PIN_MOVE_DOWN_1 PORTDbits.RD6
#define PIN_MOVE_DOWN_2 PORTDbits.RD5
#define PIN_MOVE_EAST_1 PORTBbits.RB1
#define PIN_MOVE_EAST_2 PORTBbits.RB2
#define PIN_MOVE_WEST_1 PORTBbits.RB3
#define PIN_MOVE_WEST_2 PORTBbits.RB4
#define ERR 8
Functions
void move_setup (void)
setup motors
void limit_test (void)
Move the panel to each limit to find values on pots.
void daytime_move (void)
Move the panel to point at the sun, either from sensors or memory.
void dusk_moveback (void)
Move back to the east for the next day.
void season_adjust (void)
Adjust the panel (if needed) based on the season.
void maint_move (unsigned char)
Move as directed by maintenance panel.
void motor_move (unsigned char)
Command the motors to move in the direction specified.
void day_pos_move (unsigned int)
void year_pos_move (unsigned int)
void mhurricane (void)
unsigned int abs (int)
Variables
unsigned char move = 0
varibles for debug testing, will have bits toggled depending on function entered
Macro Definition Documentation
#define ERR 8
Definition at line 29 of file movement.h.
Referenced by day_pos_move(), daytime_move(), season_adjust(), and year_pos_move().
#define PIN_MOVE_DOWN_1 PORTDbits.RD6
Definition at line 21 of file movement.h.
Referenced by motor_move().
#define PIN_MOVE_DOWN_2 PORTDbits.RD5
Definition at line 22 of file movement.h.
Referenced by motor_move().
#define PIN_MOVE_EAST_1 PORTBbits.RB1
Definition at line 24 of file movement.h.
Referenced by motor_move().
#define PIN_MOVE_EAST_2 PORTBbits.RB2
Definition at line 25 of file movement.h.
Referenced by motor_move().
#define PIN_MOVE_UP_1 PORTDbits.RD7
Definition at line 19 of file movement.h.
Referenced by motor_move().
#define PIN_MOVE_UP_2 PORTDbits.RD4
Definition at line 20 of file movement.h.
Referenced by motor_move().
#define PIN_MOVE_WEST_1 PORTBbits.RB3
Definition at line 26 of file movement.h.
Referenced by motor_move().
#define PIN_MOVE_WEST_2 PORTBbits.RB4
Definition at line 27 of file movement.h.
Referenced by motor_move().
#define PINIO_MOVE_LEFTRIGHT_1 TRISBbits.TRISB1
Definition at line 10 of file movement.h.
Referenced by move_setup().
#define PINIO_MOVE_LEFTRIGHT_2 TRISBbits.TRISB2
Definition at line 11 of file movement.h.
Referenced by move_setup().
#define PINIO_MOVE_LEFTRIGHT_3 TRISBbits.TRISB3
Definition at line 12 of file movement.h.
Referenced by move_setup().
#define PINIO_MOVE_LEFTRIGHT_4 TRISBbits.TRISB4
Definition at line 13 of file movement.h.
Referenced by move_setup().
#define PINIO_MOVE_UPDOWN_1 TRISDbits.TRISD4
Definition at line 14 of file movement.h.
Referenced by move_setup().
#define PINIO_MOVE_UPDOWN_2 TRISDbits.TRISD5
Definition at line 15 of file movement.h.
Referenced by move_setup().
#define PINIO_MOVE_UPDOWN_3 TRISDbits.TRISD6
Definition at line 16 of file movement.h.
Referenced by move_setup().
#define PINIO_MOVE_UPDOWN_4 TRISDbits.TRISD7
Definition at line 17 of file movement.h.
Referenced by move_setup().
Function Documentation
unsigned int abs (int)
Definition at line 371 of file movement.c.
Referenced by day_pos_move(), daytime_move(), limit_test(), and year_pos_move().
void day_pos_move (unsigned int)
Definition at line 339 of file movement.c.
Referenced by daytime_move(), dusk_moveback(), and limit_test().
void daytime_move (void)
Move the panel to point at the sun, either from sensors or memory.
Definition at line 103 of file movement.c.
Referenced by limit_test().
void dusk_moveback (void)
Move back to the east for the next day.
Definition at line 194 of file movement.c.
Referenced by daytime_move(), and limit_test().
void limit_test (void)
Move the panel to each limit to find values on pots.
–> Test value (global var) used to show if function was entered
Definition at line 31 of file movement.c.
void maint_move (unsigned char mcomd)
Move as directed by maintenance panel.
Inputs: desired operation of the panel
Outputs: commands to the motors
Cases
SETTINGS: will be permenant until changed by maintenance
auto = function as normal daytime_move(); set do move flag
hurricane = fixed horizantal day_pos_move(pot_noon); year_pos_move(limitPot[DOWN]); set no move flag
fixed = move to "optimal" position, day flat, year 30ish day_pos_move(pot_noon); year_pos_move((2*limitPot[DOWN]+limitPot[UP])/3); set no move flag
stop = do not move, adjust physically motor_move(STOP); set no move flag
TESTS: will default back to auto when maintenance mode exitted
auto = function as normal daytime_move();
thurricane = fixed horizantal day_pos_move(pot_noon); year_pos_move(limitPot[DOWN]);
tfixed = move to optimal position, day flat, year 30ish day_pos_move(pot_noon); year_pos_move((2*limitPot[DOWN]+limitPot[UP])/3);
limits limit_test()
Definition at line 296 of file movement.c.
void mhurricane (void)
Definition at line 380 of file movement.c.
void motor_move (unsigned char)
Command the motors to move in the direction specified.
Definition at line 201 of file movement.c.
Referenced by day_pos_move(), daytime_move(), limit_test(), limits(), mhurricane(), season_adjust(), and year_pos_move().
void move_setup (void)
setup motors
Definition at line 13 of file movement.c.
Referenced by setup().
void season_adjust (void)
Adjust the panel (if needed) based on the season.
Outputs: commands to the motors
–> Test value (global var) used to show if function was entered
Definition at line 263 of file movement.c.
Referenced by daytime_move().
void year_pos_move (unsigned int)
Definition at line 355 of file movement.c.
Referenced by limit_test().
Variable Documentation
unsigned char move = 0
varibles for debug testing, will have bits toggled depending on function entered
Definition at line 33 of file movement.h.