Sr. Design 2015: C:/Users/Benjaminp/Documents/GitHub/firmware/src/movement.c File Reference
movement.c File Reference
#include <movement.h>
Functions
void move_setup (void)
setup motors
void limit_test (void)
Move the panel to each limit to find values on pots.
void daytime_move (void)
Move the panel to point at the sun, either from sensors or memory.
void dusk_moveback (unsigned int eastLimit)
Move back to the east for the next day.
void motor_move (char direction)
void season_adjust (void)
Adjust the panel (if needed) based on the season.
void maint_move (unsigned char mcomd)
Move as directed by maintenance panel.
void day_pos_move (unsigned int desPos)
void year_pos_move (unsigned int desPos)
unsigned int abs (unsigned int num)
Function Documentation
unsigned int abs (unsigned int num)
Definition at line 356 of file movement.c.
Referenced by day_pos_move(), daytime_move(), limit_test(), and year_pos_move().
void day_pos_move (unsigned int desPos)
Definition at line 324 of file movement.c.
Referenced by daytime_move(), dusk_moveback(), and limit_test().
void daytime_move (void)
Move the panel to point at the sun, either from sensors or memory.
Definition at line 102 of file movement.c.
Referenced by limit_test(), and loop().
void dusk_moveback (unsigned int eastLimit)
Move back to the east for the next day.
Definition at line 196 of file movement.c.
Referenced by daytime_move(), and limit_test().
void limit_test (void)
Move the panel to each limit to find values on pots.
–> Test value (global var) used to show if function was entered
Definition at line 29 of file movement.c.
Referenced by setup().
void maint_move (unsigned char mcomd)
Move as directed by maintenance panel.
Inputs: desired operation of the panel
Outputs: commands to the motors
Cases
SETTINGS: will be permenant until changed by maintenance
auto = function as normal daytime_move(); set do move flag
hurricane = fixed horizantal day_pos_move(pot_noon); year_pos_move(limitPot[DOWN]); set no move flag
fixed = move to "optimal" position, day flat, year 30ish day_pos_move(pot_noon); year_pos_move((2*limitPot[DOWN]+limitPot[UP])/3); set no move flag
stop = do not move, adjust physically motor_move(STOP); set no move flag
TESTS: will default back to auto when maintenance mode exitted
auto = function as normal daytime_move();
thurricane = fixed horizantal day_pos_move(pot_noon); year_pos_move(limitPot[DOWN]);
tfixed = move to optimal position, day flat, year 30ish day_pos_move(pot_noon); year_pos_move((2*limitPot[DOWN]+limitPot[UP])/3);
limits limit_test()
Definition at line 281 of file movement.c.
void motor_move (char direction)
Definition at line 202 of file movement.c.
Referenced by day_pos_move(), daytime_move(), limit_test(), limits(), season_adjust(), and year_pos_move().
void move_setup (void)
setup motors
Definition at line 12 of file movement.c.
Referenced by setup().
void season_adjust (void)
Adjust the panel (if needed) based on the season.
Outputs: commands to the motors
–> Test value (global var) used to show if function was entered
Definition at line 248 of file movement.c.
Referenced by daytime_move().
void year_pos_move (unsigned int desPos)
Definition at line 340 of file movement.c.
Referenced by limit_test().