Sr. Design 2015: C:/Users/Benjaminp/Documents/GitHub/firmware/include/rtc.h File Reference
rtc.h File Reference
Data Structures
struct datetime
structure to save the date and time into a single variable in normal binary format (Not BCD!)
struct alarmtime
Macros
#define REFDAY 2
#define HALFSECOND 0
#define ONESECOND 1
#define TENSECOND 2
#define MINUTE 3
#define TENMINUTES 4
#define HOURLY 5
#define DAILY 6
#define WEEKLY 7
#define MONTHLY 8
#define YEARLY 9
Functions
void rtc_setup (void)
Real-time Clock/Calendar Module setup.
unsigned rtc_set (datetime)
Set the time on the RTCC.
unsigned rtc_get (datetime *)
gives the current time as a datetime structure.
unsigned alarm_set (alarmtime)
Set the alarm date/time.
unsigned alarm_enable ()
Enables the alarm. Make sure to setup the alarm first!
unsigned alarm_disable ()
Disable the alarm.
Macro Definition Documentation
#define DAILY 6
Definition at line 20 of file rtc.h.
#define HALFSECOND 0
Definition at line 14 of file rtc.h.
#define HOURLY 5
Definition at line 19 of file rtc.h.
#define MINUTE 3
Definition at line 17 of file rtc.h.
#define MONTHLY 8
Definition at line 22 of file rtc.h.
#define ONESECOND 1
Definition at line 15 of file rtc.h.
#define REFDAY 2
Definition at line 11 of file rtc.h.
#define TENMINUTES 4
Definition at line 18 of file rtc.h.
#define TENSECOND 2
Definition at line 16 of file rtc.h.
#define WEEKLY 7
Definition at line 21 of file rtc.h.
#define YEARLY 9
Definition at line 23 of file rtc.h.
Function Documentation
unsigned alarm_disable ()
Disable the alarm.
Output: Returns false if the alarm was set before. If it was not, returns true.
Definition at line 176 of file rtc.c.
Referenced by alarm_set().
unsigned alarm_enable ()
Enables the alarm. Make sure to setup the alarm first!
Output: A bit specifying whether the alarm was enabled correcty. If the RTCC is off, the RTCC is not setup, or the alarm has not been setup, it will return true.
Definition at line 165 of file rtc.c.
unsigned alarm_set (alarmtime time)
Set the alarm date/time.
Todo:
TODO: Documentation for the alarm needs done. sign LNB.
Input: an alarmtime structure containing the time, date, repetitions (if applicable) and frequency Output: A single bit specifying success (false). If something is invalid, the function will return true.
Please see section 17 in the datasheet, particularly figure 17-5, for more detail.
Definition at line 61 of file rtc.c.
unsigned rtc_get (datetime *)
gives the current time as a datetime structure.
Definition at line 39 of file rtc.c.
Referenced by daytime_move(), limit_test(), and pir().
unsigned rtc_set (datetime time)
Set the time on the RTCC.
Inputs: a datetime structure containing the year, month, day, hour, minute, and second. Outputs: A single bit. Probably will never return failure. Detailed Description: Note: Will convert the numbers to BCD endcoding before returning them
Definition at line 19 of file rtc.c.
void rtc_setup (void)
Real-time Clock/Calendar Module setup.
Todo:
TODO: Check to see if the rtcc is setup already
Definition at line 5 of file rtc.c.
Referenced by setup().