Sr. Design 2015: C:/Users/Benjaminp/Documents/GitHub/firmware.X/src/sensors.c File Reference
sensors.c File Reference
#include <sensors.h>
#include <rtc.h>
#include <light.h>
#include <shared.h>
#include <movement.h>
#include <eeprom.h>
Functions
void sensor_setup (void)
setup sensors
unsigned int photo_value (unsigned char photonum, unsigned update)
Check the analog value of a particular photoresistor.
unsigned char temperature (void)
Check the temperature inside the enclosure.
unsigned int ang_pos (unsigned potnum, unsigned update)
Check the analog value of a particular potentimeter.
unsigned pir (void)
check the PIR sensor and turn light LED_ON or DIM depending on motion Only active during night time state
unsigned char limits (void)
Function Documentation
unsigned int ang_pos (unsigned potnum, unsigned update)
Check the analog value of a particular potentimeter.
Inputs: designator of potentimeter to be checked (1 or 2)
Outputs: analog value off that potentimeter in binary
–> Test values (returns) used to show if function preformed as desired
Definition at line 117 of file sensors.c.
Referenced by day_pos_move(), daytime_move(), limit_test(), and year_pos_move().
unsigned char limits (void)
Definition at line 201 of file sensors.c.
Referenced by limit_test(), and mhurricane().
unsigned int photo_value (unsigned char photonum, unsigned update)
Check the analog value of a particular photoresistor.
Inputs: designator of photoresistor to be checked (1, 2, 3, or 4)
Outputs: analog value off that photoresistor in binary
–> Test values (returns) used to show if function preformed as desired
Definition at line 50 of file sensors.c.
Referenced by daytime_move(), limit_test(), and season_adjust().
unsigned pir (void)
check the PIR sensor and turn light LED_ON or DIM depending on motion Only active during night time state
Inputs: none
Outputs: Bit value showing if movement is detected or not
Definition at line 149 of file sensors.c.
Referenced by loop().
void sensor_setup (void)
setup sensors
Definition at line 11 of file sensors.c.
Referenced by setup().
unsigned char temperature (void)
Check the temperature inside the enclosure.
Outputs: Temperature at the sensor in degF
–> Test value (return) used to show if function preformed as desired
Definition at line 97 of file sensors.c.