Sr. Design 2015: C:/Users/Benjaminp/Documents/GitHub/firmware.X/src/shared.c File Reference
shared.c File Reference
#include <shared.h>
Functions
void adc_setup ()
Setup the ADC module.
unsigned int adc_read (unsigned char channel)
Read adc value out of the ADC buffer for the passed channel.
void pwm_setup ()
Setup TMR2 for use by all the CCP modules.
unsigned pwm_set (unsigned char channel, unsigned int duty)
Sets a specific pwm channel to a certain duty cycle in %.
unsigned i2c_tx (unsigned char addr, unsigned char reg16, unsigned char regl, unsigned char regh, unsigned char *data, unsigned int dataLength)
Takes a packet and transmits it according to its contents. Returns true if successful.
unsigned i2c_check (unsigned char addr)
Checks to see if there is something at a certain address. Returns the acknowledge bit (0=ack)
unsigned i2c_rx (unsigned char addr, unsigned char reg16, unsigned char regl, unsigned char regh, unsigned char *data, unsigned int dataLength)
Gets Data from a slave at a specific address. Returns a char array pointer.
void i2c_setup ()
Set up the i2c1 module.
void i2c_lcdInit ()
void delay (unsigned int times)
delay(#): delay #/8 seconds
void timeoutInit ()
Reset the timer variable and the timer counter so we can do a timeout.
unsigned timeoutCheck (unsigned int timeCheck)
Check if we have waited a certain ammount of time.
Detailed Description
This file containes the functions that are used in more than one file. This includes the ADC, I2C, and PWM. Author: Benjamin Plain
Definition in file shared.c.
Function Documentation
unsigned int adc_read (unsigned char channel)
Read adc value out of the ADC buffer for the passed channel.
The only channels we need are 0,2,3,4,8,17,18,19.
Definition at line 32 of file shared.c.
Referenced by ang_pos(), menu_alarm_battery(), menu_battVoltage(), photo_value(), power_loop(), and temperature().
void adc_setup (void)
Setup the ADC module.
Definition at line 11 of file shared.c.
Referenced by setup().
void delay (unsigned int times)
delay(#): delay #/8 seconds
To use the delay and timeout functions, take the time you want to wait in seconds and divide it by 8. This is the number you put in (up to 65535 => 2.27 hours). The delay function is simple to use, but blocks the code from running. The timeout functions do not block. To use timeout functionality, use timeoutInit() first, then call timeoutCheck like the delay. It will return false when the timeout has been reached.
Definition at line 319 of file shared.c.
Referenced by lcd_begin(), menu_getSelection(), menu_setACBatt(), menu_setHurricaneMode(), menu_setLightMode(), and menu_setPanelMode().
unsigned i2c_check (unsigned char addr)
Checks to see if there is something at a certain address. Returns the acknowledge bit (0=ack)
Inputs: The address of the device on the i2c bus
Definition at line 172 of file shared.c.
Referenced by mem_check().
void i2c_lcdInit (void)
Definition at line 278 of file shared.c.
unsigned i2c_rx (unsigned char addr, unsigned char reg16, unsigned char regl, unsigned char regh, unsigned char * data, unsigned int dataLength)
Gets Data from a slave at a specific address. Returns a char array pointer.
Inputs: packet: A packet consisting of an address, a number for quantity, and an array to fill with the quantity. Outputs: None formally. Modifies the data portion of the packet pointer that was given.
Definition at line 185 of file shared.c.
void i2c_setup (void)
Set up the i2c1 module.
Definition at line 208 of file shared.c.
Referenced by setup().
unsigned i2c_tx (unsigned char addr, unsigned char reg16, unsigned char regl, unsigned char regh, unsigned char * data, unsigned int dataLength)
Takes a packet and transmits it according to its contents. Returns true if successful.
Inputs: a i2c transmission packet (consists of address and array of data)
Outputs: a single bit specifying failure or success
Description: This function takes the packet and transmits the packet.addr byte first. It then transmits packet.dataLength bytes from the packet.data array. If at any time a byte is not acknowleged, the function will return 0 (false).
Todo:
TODO: Get the ack bit and return that from the address at least.
Definition at line 151 of file shared.c.
Referenced by lcd_display().
unsigned pwm_set (unsigned char channel, unsigned int duty)
Sets a specific pwm channel to a certain duty cycle in %.
Inputs: Channel - which PWM channel to use, duty - the duty cycle (duty/256). Channels 1 and 2 are the motor drivers (using the 2 ECCP modules in full bridge mode) Channel 3 is for the light (using normal CCP PWM module) Channel 4,5,6 are for the LCD Backlight (Using PWM modules)
Outputs: A single bit specifying whether or not the command succeded (1 = success)
DutyCycle = ((CCPR4L:CCP4CON<5:4>) * TOSC * (TMR2 Prescale Value) DutyCycle = Value * 64000000/ 4 / 16 Value = 1000000/dutyCycle
Definition at line 110 of file shared.c.
Referenced by lcd_background(), led(), led_setup(), menu_setDimLength(), and menu_setDimLevel().
void pwm_setup (void)
Setup TMR2 for use by all the CCP modules.
Definition at line 48 of file shared.c.
Referenced by setup().
unsigned timeoutCheck (unsigned int timeCheck)
Check if we have waited a certain ammount of time.
Definition at line 337 of file shared.c.
Referenced by menu_setTime(), menu_setXaxis(), and menu_setYaxis().
void timeoutInit (void)
Reset the timer variable and the timer counter so we can do a timeout.
Definition at line 328 of file shared.c.
Referenced by menu_setTime(), menu_setXaxis(), and menu_setYaxis().