Sr. Design 2015: C:/Users/Benjaminp/Documents/GitHub/firmware.X/include/shared.h File Reference
shared.h File Reference
#include <xc.h>
Data Structures
struct i2cPacket
A packet that contains an address (8 or 10bit), a data array, and how long the array is.
Macros
#define COMPANY "Patience, Inc."
#define FIRMWARE_VERSION "Firmware Ver: 1.0b"
#define ADDRESS 0x05
Address for communicaiton between poles.
#define true 1
#define false 0
#define ANPHOTO1 7
#define ANPHOTO2 12
#define ANPHOTO3 13
#define ANPHOTO4 14
#define ANPOT1 3
#define ANPOT2 2
#define ANBATT 5
#define ANTEMP 0
#define _XTAL_FREQ 32000000
System frequency is 32MHz. USB is at 48MHz.
Functions
void adc_setup (void)
Setup the ADC module.
unsigned int adc_read (unsigned char)
Read adc value out of the ADC buffer for the passed channel.
void pwm_setup (void)
Setup TMR2 for use by all the CCP modules.
unsigned pwm_set (unsigned char, unsigned int)
Sets a specific pwm channel to a certain duty cycle in %.
void i2c_setup (void)
Set up the i2c1 module.
unsigned i2c_tx (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char *, unsigned int)
Takes a packet and transmits it according to its contents. Returns true if successful.
unsigned i2c_rx (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char *, unsigned int)
Gets Data from a slave at a specific address. Returns a char array pointer.
unsigned i2c_check (unsigned char)
Checks to see if there is something at a certain address. Returns the acknowledge bit (0=ack)
void i2c_lcdInit (void)
void delay (unsigned int)
delay(#): delay #/8 seconds
void timeoutInit (void)
Reset the timer variable and the timer counter so we can do a timeout.
unsigned timeoutCheck (unsigned int)
Check if we have waited a certain ammount of time.
Variables
struct {
unsigned rtcInit: 1
unsigned alarmInit: 1
unsigned mmode: 2
unsigned state: 2
unsigned sleepable: 1
unsigned __pad0__: 1
} status
The first status byte - Includes the two state machine states, the rtc initialization state, and whether or not the loop will sleep at the end.
unsigned char myAddr
volatile unsigned int time
volatile unsigned int delayTime
Macro Definition Documentation
#define _XTAL_FREQ 32000000
System frequency is 32MHz. USB is at 48MHz.
Definition at line 30 of file shared.h.
#define ADDRESS 0x05
Address for communicaiton between poles.
Definition at line 15 of file shared.h.
#define ANBATT 5
Definition at line 26 of file shared.h.
Referenced by menu_alarm_battery(), menu_battVoltage(), and power_loop().
#define ANPHOTO1 7
Definition at line 20 of file shared.h.
#define ANPHOTO2 12
Definition at line 21 of file shared.h.
#define ANPHOTO3 13
Definition at line 22 of file shared.h.
#define ANPHOTO4 14
Definition at line 23 of file shared.h.
#define ANPOT1 3
Definition at line 24 of file shared.h.
#define ANPOT2 2
Definition at line 25 of file shared.h.
#define ANTEMP 0
Definition at line 27 of file shared.h.
#define COMPANY "Patience, Inc."
Definition at line 11 of file shared.h.
#define false 0
Definition at line 18 of file shared.h.
#define FIRMWARE_VERSION "Firmware Ver: 1.0b"
Definition at line 12 of file shared.h.
#define true 1
Definition at line 17 of file shared.h.
Function Documentation
unsigned int adc_read (unsigned char channel)
Read adc value out of the ADC buffer for the passed channel.
The only channels we need are 0,2,3,4,8,17,18,19.
Definition at line 32 of file shared.c.
Referenced by ang_pos(), menu_alarm_battery(), menu_battVoltage(), photo_value(), power_loop(), and temperature().
void adc_setup (void)
Setup the ADC module.
Definition at line 11 of file shared.c.
Referenced by setup().
void delay (unsigned int times)
delay(#): delay #/8 seconds
To use the delay and timeout functions, take the time you want to wait in seconds and divide it by 8. This is the number you put in (up to 65535 => 2.27 hours). The delay function is simple to use, but blocks the code from running. The timeout functions do not block. To use timeout functionality, use timeoutInit() first, then call timeoutCheck like the delay. It will return false when the timeout has been reached.
Definition at line 319 of file shared.c.
Referenced by lcd_begin(), menu_getSelection(), menu_setACBatt(), menu_setHurricaneMode(), menu_setLightMode(), and menu_setPanelMode().
unsigned i2c_check (unsigned char addr)
Checks to see if there is something at a certain address. Returns the acknowledge bit (0=ack)
Inputs: The address of the device on the i2c bus
Definition at line 172 of file shared.c.
Referenced by mem_check().
void i2c_lcdInit (void)
Definition at line 278 of file shared.c.
unsigned i2c_rx (unsigned char addr, unsigned char reg16, unsigned char regl, unsigned char regh, unsigned char * data, unsigned int dataLength)
Gets Data from a slave at a specific address. Returns a char array pointer.
Inputs: packet: A packet consisting of an address, a number for quantity, and an array to fill with the quantity. Outputs: None formally. Modifies the data portion of the packet pointer that was given.
Definition at line 185 of file shared.c.
void i2c_setup (void)
Set up the i2c1 module.
Definition at line 208 of file shared.c.
Referenced by setup().
unsigned i2c_tx (unsigned char addr, unsigned char reg16, unsigned char regl, unsigned char regh, unsigned char * data, unsigned int dataLength)
Takes a packet and transmits it according to its contents. Returns true if successful.
Inputs: a i2c transmission packet (consists of address and array of data)
Outputs: a single bit specifying failure or success
Description: This function takes the packet and transmits the packet.addr byte first. It then transmits packet.dataLength bytes from the packet.data array. If at any time a byte is not acknowleged, the function will return 0 (false).
Todo:
TODO: Get the ack bit and return that from the address at least.
Definition at line 151 of file shared.c.
Referenced by lcd_display().
unsigned pwm_set (unsigned char channel, unsigned int duty)
Sets a specific pwm channel to a certain duty cycle in %.
Inputs: Channel - which PWM channel to use, duty - the duty cycle (duty/256). Channels 1 and 2 are the motor drivers (using the 2 ECCP modules in full bridge mode) Channel 3 is for the light (using normal CCP PWM module) Channel 4,5,6 are for the LCD Backlight (Using PWM modules)
Outputs: A single bit specifying whether or not the command succeded (1 = success)
DutyCycle = ((CCPR4L:CCP4CON<5:4>) * TOSC * (TMR2 Prescale Value) DutyCycle = Value * 64000000/ 4 / 16 Value = 1000000/dutyCycle
Definition at line 110 of file shared.c.
Referenced by lcd_background(), led(), led_setup(), menu_setDimLength(), and menu_setDimLevel().
void pwm_setup (void)
Setup TMR2 for use by all the CCP modules.
Definition at line 48 of file shared.c.
Referenced by setup().
unsigned timeoutCheck (unsigned int)
Check if we have waited a certain ammount of time.
Definition at line 337 of file shared.c.
Referenced by menu_setTime(), menu_setXaxis(), and menu_setYaxis().
void timeoutInit (void)
Reset the timer variable and the timer counter so we can do a timeout.
Definition at line 328 of file shared.c.
Referenced by menu_setTime(), menu_setXaxis(), and menu_setYaxis().
Variable Documentation
unsigned __pad0__
Definition at line 43 of file shared.h.
unsigned alarmInit
Definition at line 39 of file shared.h.
volatile unsigned int delayTime
Definition at line 47 of file shared.h.
Referenced by delay(), and isr_high().
unsigned mmode
Definition at line 40 of file shared.h.
unsigned char myAddr
Definition at line 46 of file shared.h.
Referenced by isr(), and menu_setAddr().
unsigned rtcInit
Definition at line 38 of file shared.h.
unsigned sleepable
Definition at line 42 of file shared.h.
unsigned state
Definition at line 41 of file shared.h.
volatile { ... } status
The first status byte - Includes the two state machine states, the rtc initialization state, and whether or not the loop will sleep at the end.
Referenced by alarm_enable(), alarm_set(), hid_loop(), isr(), lcd_begin(), lcd_end(), loop(), menu_display(), rtc_set(), and rtc_setup().
volatile unsigned int time
Definition at line 47 of file shared.h.
Referenced by isr_high(), timeoutCheck(), and timeoutInit().