Sr. Design 2015: C:/Users/Benjaminp/Documents/GitHub/firmware/include/solarLight.h File Reference
solarLight.h File Reference
#include <shared.h>
#include <communication.h>
#include <eeprom.h>
#include <hid.h>
#include <lcd.h>
#include <movement.h>
#include <powerman.h>
#include <rtc.h>
#include <sensors.h>
#include <usb/usb_device_cdc.h>
Macros
#define LED_PIN TRISCbits.TRISC7
#define LED_OUT PORTCbits.RC7
#define LED_CHAN 7
#define LED_DUTY_OFF 100
#define LED_DUTY_DIM 14
#define LED_DUTY_ON 0
Functions
void setup (void)
Run all the setup routines. Initialize stuff here without any interrupts.
void loop (void)
void interrupt low_priority isr_low (void)
void interrupt high_priority isr_high (void)
void led_setup (void)
setup for light
void led (unsigned char)
Macro Definition Documentation
#define LED_CHAN 7
Definition at line 19 of file solarLight.h.
Referenced by led().
#define LED_DUTY_DIM 14
Definition at line 21 of file solarLight.h.
Referenced by led().
#define LED_DUTY_OFF 100
Definition at line 20 of file solarLight.h.
Referenced by led().
#define LED_DUTY_ON 0
Definition at line 22 of file solarLight.h.
Referenced by led().
#define LED_OUT PORTCbits.RC7
Definition at line 17 of file solarLight.h.
#define LED_PIN TRISCbits.TRISC7
Definition at line 16 of file solarLight.h.
Referenced by led_setup().
Function Documentation
void interrupt high_priority isr_high (void)
void interrupt low_priority isr_low (void)
void led (unsigned char)
Definition at line 348 of file solarLight.c.
Referenced by loop(), and pir().
void led_setup (void)
setup for light
–> Test value (global var) used to show if function was entered
setup for light
Items that are dealt with in this ISR:
none yet
Make sure to enable priority interrupts before using this routine.
Definition at line 7 of file light.c.
Referenced by setup().
void loop (void)
/brief The MAIN loop that executes EVERYTHING!
No inputs or outputs besides what goes in and out of the pins.
Definition at line 135 of file solarLight.c.
Referenced by main().
void setup (void)
Run all the setup routines. Initialize stuff here without any interrupts.
Todo:
TODO: Check to see if the chip started after a POR, BOR, or is from VBATT
Definition at line 106 of file solarLight.c.
Referenced by main().